import { BiasRule } from './types';

export const biasRules: BiasRule[] = [
  // ── XAUUSD (Gold) ──────────────────────────────────────
  { eventCategory: 'fed_tone', eventValue: 'hawkish', symbol: 'XAUUSD', scoreChange: -30 },
  { eventCategory: 'fed_tone', eventValue: 'dovish', symbol: 'XAUUSD', scoreChange: 30 },
  { eventCategory: 'dollar_strength', eventValue: 'strong', symbol: 'XAUUSD', scoreChange: -25 },
  { eventCategory: 'dollar_strength', eventValue: 'weak', symbol: 'XAUUSD', scoreChange: 25 },
  { eventCategory: 'yields', eventValue: 'rising', symbol: 'XAUUSD', scoreChange: -20 },
  { eventCategory: 'yields', eventValue: 'falling', symbol: 'XAUUSD', scoreChange: 20 },
  { eventCategory: 'inflation', eventValue: 'high', symbol: 'XAUUSD', scoreChange: -15 },
  { eventCategory: 'inflation', eventValue: 'low', symbol: 'XAUUSD', scoreChange: 15 },
  { eventCategory: 'employment', eventValue: 'strong', symbol: 'XAUUSD', scoreChange: -10 },
  { eventCategory: 'employment', eventValue: 'weak', symbol: 'XAUUSD', scoreChange: 10 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_off', symbol: 'XAUUSD', scoreChange: 25 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_on', symbol: 'XAUUSD', scoreChange: -10 },
  { eventCategory: 'geopolitical', eventValue: 'tension', symbol: 'XAUUSD', scoreChange: 30 },
  { eventCategory: 'geopolitical', eventValue: 'easing', symbol: 'XAUUSD', scoreChange: -15 },
  { eventCategory: 'gdp', eventValue: 'beat', symbol: 'XAUUSD', scoreChange: -10 },
  { eventCategory: 'gdp', eventValue: 'miss', symbol: 'XAUUSD', scoreChange: 10 },
  { eventCategory: 'retail_sales', eventValue: 'beat', symbol: 'XAUUSD', scoreChange: -10 },
  { eventCategory: 'retail_sales', eventValue: 'miss', symbol: 'XAUUSD', scoreChange: 10 },
  { eventCategory: 'pmi', eventValue: 'beat', symbol: 'XAUUSD', scoreChange: -10 },
  { eventCategory: 'pmi', eventValue: 'miss', symbol: 'XAUUSD', scoreChange: 10 },

  // ── GBPUSD ─────────────────────────────────────────────
  { eventCategory: 'fed_tone', eventValue: 'hawkish', symbol: 'GBPUSD', scoreChange: -15 },
  { eventCategory: 'fed_tone', eventValue: 'dovish', symbol: 'GBPUSD', scoreChange: 15 },
  { eventCategory: 'boe_tone', eventValue: 'hawkish', symbol: 'GBPUSD', scoreChange: 30 },
  { eventCategory: 'boe_tone', eventValue: 'dovish', symbol: 'GBPUSD', scoreChange: -30 },
  { eventCategory: 'dollar_strength', eventValue: 'strong', symbol: 'GBPUSD', scoreChange: -20 },
  { eventCategory: 'dollar_strength', eventValue: 'weak', symbol: 'GBPUSD', scoreChange: 20 },
  { eventCategory: 'inflation', eventValue: 'high', symbol: 'GBPUSD', scoreChange: 15 },
  { eventCategory: 'inflation', eventValue: 'low', symbol: 'GBPUSD', scoreChange: -15 },
  { eventCategory: 'inflation', eventValue: 'high', symbol: 'GBPUSD', scoreChange: -15, country: 'US' },
  { eventCategory: 'inflation', eventValue: 'low', symbol: 'GBPUSD', scoreChange: 15, country: 'US' },
  { eventCategory: 'inflation', eventValue: 'high', symbol: 'GBPUSD', scoreChange: 15, country: 'GB' },
  { eventCategory: 'inflation', eventValue: 'low', symbol: 'GBPUSD', scoreChange: -15, country: 'GB' },
  { eventCategory: 'inflation', eventValue: 'high', symbol: 'GBPUSD', scoreChange: 15, country: 'UK' },
  { eventCategory: 'inflation', eventValue: 'low', symbol: 'GBPUSD', scoreChange: -15, country: 'UK' },
  { eventCategory: 'employment', eventValue: 'strong', symbol: 'GBPUSD', scoreChange: 10 },
  { eventCategory: 'employment', eventValue: 'weak', symbol: 'GBPUSD', scoreChange: -10 },
  { eventCategory: 'employment', eventValue: 'strong', symbol: 'GBPUSD', scoreChange: -10, country: 'US' },
  { eventCategory: 'employment', eventValue: 'weak', symbol: 'GBPUSD', scoreChange: 10, country: 'US' },
  { eventCategory: 'employment', eventValue: 'strong', symbol: 'GBPUSD', scoreChange: 10, country: 'GB' },
  { eventCategory: 'employment', eventValue: 'weak', symbol: 'GBPUSD', scoreChange: -10, country: 'GB' },
  { eventCategory: 'employment', eventValue: 'strong', symbol: 'GBPUSD', scoreChange: 10, country: 'UK' },
  { eventCategory: 'employment', eventValue: 'weak', symbol: 'GBPUSD', scoreChange: -10, country: 'UK' },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_off', symbol: 'GBPUSD', scoreChange: -10 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_on', symbol: 'GBPUSD', scoreChange: 10 },
  { eventCategory: 'gdp', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: 15 },
  { eventCategory: 'gdp', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: -15 },
  { eventCategory: 'gdp', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: -15, country: 'US' },
  { eventCategory: 'gdp', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: 15, country: 'US' },
  { eventCategory: 'gdp', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: 15, country: 'GB' },
  { eventCategory: 'gdp', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: -15, country: 'GB' },
  { eventCategory: 'gdp', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: 15, country: 'UK' },
  { eventCategory: 'gdp', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: -15, country: 'UK' },
  { eventCategory: 'pmi', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: 10 },
  { eventCategory: 'pmi', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: -10 },
  { eventCategory: 'pmi', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: -10, country: 'US' },
  { eventCategory: 'pmi', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: 10, country: 'US' },
  { eventCategory: 'pmi', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: 10, country: 'GB' },
  { eventCategory: 'pmi', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: -10, country: 'GB' },
  { eventCategory: 'pmi', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: 10, country: 'UK' },
  { eventCategory: 'pmi', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: -10, country: 'UK' },
  { eventCategory: 'retail_sales', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: -10, country: 'US' },
  { eventCategory: 'retail_sales', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: 10, country: 'US' },
  { eventCategory: 'retail_sales', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: 10, country: 'GB' },
  { eventCategory: 'retail_sales', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: -10, country: 'GB' },
  { eventCategory: 'retail_sales', eventValue: 'beat', symbol: 'GBPUSD', scoreChange: 10, country: 'UK' },
  { eventCategory: 'retail_sales', eventValue: 'miss', symbol: 'GBPUSD', scoreChange: -10, country: 'UK' },
  { eventCategory: 'yields', eventValue: 'rising', symbol: 'GBPUSD', scoreChange: -10 },
  { eventCategory: 'yields', eventValue: 'falling', symbol: 'GBPUSD', scoreChange: 10 },

  // ── US100 (Nasdaq) ─────────────────────────────────────
  { eventCategory: 'fed_tone', eventValue: 'hawkish', symbol: 'US100', scoreChange: -40 },
  { eventCategory: 'fed_tone', eventValue: 'dovish', symbol: 'US100', scoreChange: 40 },
  { eventCategory: 'dollar_strength', eventValue: 'strong', symbol: 'US100', scoreChange: -10 },
  { eventCategory: 'dollar_strength', eventValue: 'weak', symbol: 'US100', scoreChange: 10 },
  { eventCategory: 'yields', eventValue: 'rising', symbol: 'US100', scoreChange: -30 },
  { eventCategory: 'yields', eventValue: 'falling', symbol: 'US100', scoreChange: 30 },
  { eventCategory: 'inflation', eventValue: 'high', symbol: 'US100', scoreChange: -25 },
  { eventCategory: 'inflation', eventValue: 'low', symbol: 'US100', scoreChange: 25 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_off', symbol: 'US100', scoreChange: -30 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_on', symbol: 'US100', scoreChange: 25 },
  { eventCategory: 'employment', eventValue: 'strong', symbol: 'US100', scoreChange: 10 },
  { eventCategory: 'employment', eventValue: 'weak', symbol: 'US100', scoreChange: -10 },
  { eventCategory: 'earnings', eventValue: 'positive', symbol: 'US100', scoreChange: 20 },
  { eventCategory: 'earnings', eventValue: 'negative', symbol: 'US100', scoreChange: -20 },
  { eventCategory: 'gdp', eventValue: 'beat', symbol: 'US100', scoreChange: 10 },
  { eventCategory: 'gdp', eventValue: 'miss', symbol: 'US100', scoreChange: -20 },
  { eventCategory: 'pmi', eventValue: 'beat', symbol: 'US100', scoreChange: 10 },
  { eventCategory: 'pmi', eventValue: 'miss', symbol: 'US100', scoreChange: -10 },
  { eventCategory: 'retail_sales', eventValue: 'beat', symbol: 'US100', scoreChange: 10 },
  { eventCategory: 'retail_sales', eventValue: 'miss', symbol: 'US100', scoreChange: -10 },

  // ── DJ30 (Dow Jones) ───────────────────────────────────
  { eventCategory: 'fed_tone', eventValue: 'hawkish', symbol: 'DJ30', scoreChange: -25 },
  { eventCategory: 'fed_tone', eventValue: 'dovish', symbol: 'DJ30', scoreChange: 25 },
  { eventCategory: 'dollar_strength', eventValue: 'strong', symbol: 'DJ30', scoreChange: -5 },
  { eventCategory: 'dollar_strength', eventValue: 'weak', symbol: 'DJ30', scoreChange: 5 },
  { eventCategory: 'yields', eventValue: 'rising', symbol: 'DJ30', scoreChange: -15 },
  { eventCategory: 'yields', eventValue: 'falling', symbol: 'DJ30', scoreChange: 15 },
  { eventCategory: 'inflation', eventValue: 'high', symbol: 'DJ30', scoreChange: -20 },
  { eventCategory: 'inflation', eventValue: 'low', symbol: 'DJ30', scoreChange: 20 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_off', symbol: 'DJ30', scoreChange: -20 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_on', symbol: 'DJ30', scoreChange: 20 },
  { eventCategory: 'employment', eventValue: 'strong', symbol: 'DJ30', scoreChange: 15 },
  { eventCategory: 'employment', eventValue: 'weak', symbol: 'DJ30', scoreChange: -15 },
  { eventCategory: 'gdp', eventValue: 'beat', symbol: 'DJ30', scoreChange: 15 },
  { eventCategory: 'gdp', eventValue: 'miss', symbol: 'DJ30', scoreChange: -20 },
  { eventCategory: 'retail_sales', eventValue: 'beat', symbol: 'DJ30', scoreChange: 10 },
  { eventCategory: 'retail_sales', eventValue: 'miss', symbol: 'DJ30', scoreChange: -10 },
  { eventCategory: 'pmi', eventValue: 'beat', symbol: 'DJ30', scoreChange: 10 },
  { eventCategory: 'pmi', eventValue: 'miss', symbol: 'DJ30', scoreChange: -10 },

  // ── BTCUSD ─────────────────────────────────────────────
  { eventCategory: 'fed_tone', eventValue: 'hawkish', symbol: 'BTCUSD', scoreChange: -25 },
  { eventCategory: 'fed_tone', eventValue: 'dovish', symbol: 'BTCUSD', scoreChange: 30 },
  { eventCategory: 'dollar_strength', eventValue: 'strong', symbol: 'BTCUSD', scoreChange: -15 },
  { eventCategory: 'dollar_strength', eventValue: 'weak', symbol: 'BTCUSD', scoreChange: 15 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_on', symbol: 'BTCUSD', scoreChange: 25 },
  { eventCategory: 'risk_sentiment', eventValue: 'risk_off', symbol: 'BTCUSD', scoreChange: -20 },
  { eventCategory: 'crypto_regulation', eventValue: 'positive', symbol: 'BTCUSD', scoreChange: 35 },
  { eventCategory: 'crypto_regulation', eventValue: 'negative', symbol: 'BTCUSD', scoreChange: -40 },
  { eventCategory: 'yields', eventValue: 'rising', symbol: 'BTCUSD', scoreChange: -15 },
  { eventCategory: 'yields', eventValue: 'falling', symbol: 'BTCUSD', scoreChange: 15 },
  { eventCategory: 'inflation', eventValue: 'high', symbol: 'BTCUSD', scoreChange: -10 },
  { eventCategory: 'inflation', eventValue: 'low', symbol: 'BTCUSD', scoreChange: 10 },
  { eventCategory: 'employment', eventValue: 'strong', symbol: 'BTCUSD', scoreChange: 5 },
  { eventCategory: 'employment', eventValue: 'weak', symbol: 'BTCUSD', scoreChange: -10 },
  { eventCategory: 'gdp', eventValue: 'beat', symbol: 'BTCUSD', scoreChange: 5 },
  { eventCategory: 'gdp', eventValue: 'miss', symbol: 'BTCUSD', scoreChange: -10 },
];
